name: LastInventory
main: CodsXBlastin\LastInventory\Loader
description: A JSON based Last Inventory System
author: CodsXBlastin
api: 4.0.0
version: 2.0.0
load: POSTWORLD
website: github.com/codsxblastin
permissions:
  lastinventory.command:
    default: op
    description: LastInventory Root Permission
